---
- name: Create /etc/borgmatic folder
  ansible.builtin.file:
    path: /etc/borgmatic
    state: directory
    owner: root
    group: root
    mode: "0700"
- name: Write borgmatic config
  template:
    src: config.yaml.j2
    dest: /etc/borgmatic/config.yaml
    owner: root
    group: root
    mode: "0600"
- name: Create /root/.borgmatic folder
  ansible.builtin.file:
    path: /root/.borgmatic
    state: directory
    owner: root
    group: root
    mode: "0700"
- name: "Copy SSH key {{ item }} to borgmatic config folder"
  ansible.builtin.copy:
    src: "ssh_keys/{{ item }}"
    dest: "/etc/borgmatic/{{ item }}"
    owner: root
    group: root
    mode: "0600"
  loop: "{{ borgmatic_ssh_keys }}"
