---
- name: Create /etc/borgmatic folder
  ansible.builtin.file:
    path: /etc/borgmatic
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Write borgmatic config
  copy:
    dest: /etc/borgmatic/config.yaml
    owner: root
    group: root
    mode: "0600"
    content: "{{ borgmatic_config | to_nice_yaml(width=50, explicit_start=True, explicit_end=True) }}"

- name: Create /root/.borgmatic folder
  ansible.builtin.file:
    path: /root/.borgmatic
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: "Copy SSH key {{ item }} to borgmatic config folder"
  ansible.builtin.copy:
    src: "ssh_keys/{{ item }}"
    dest: "/etc/borgmatic/{{ item }}"
    owner: root
    group: root
    mode: "0600"
  loop: "{{ borgmatic_ssh_keys }}"
